spring:
  messages:
    basename: messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onezo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jwt:
    secret: jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912jj0912

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#toss 암호화 적용 하기
toss:
  client:
    id: test_ck_4yKeq5bgrp5m5N6vb0oL8GX0lzW6
    secret: test_sk_oEjb0gm23PW4ABRA5w9W8pGwBJn5
    successUrl: "http://localhost:8080/v1/api/payment/success"
    failUrl: "http://localhost:8080/v1/api/payment/fail"
    OriginUrl: "https://api.tosspayments.com/v1/payments/"

jasypt:
  encryptor:
    password: wasdjlkjoIQHNWLIUEOqkA;XDLJakldmaSL

#이거 꼭 자시프트 해서 깃허브에 올리기
#프론트쪽에 client_id restapi 키 넣어줘야됨
kakao:
  client:
    id: ee6034fee6eaca2e42ce04b136729cf7
    secret: i25c2321Aa5A9Jy1r6AgrOj2SihPO0Jn
    redirect: http://loaclhost:8080/oauth/kakao/callback
